name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  WEBRTC_VERSION: m146.7680.1.0
  WEBRTC_PLATFORM: windows_x86_64
  FFMPEG_RELEASE_TAG: autobuild-2026-03-15-12-59
  FFMPEG_PACKAGE_VERSION: n7.1.3-43-g5a1f107b4c
  FFMPEG_PACKAGE_TARGET: win64-lgpl-shared-7.1
  VCPKG_TARGET_TRIPLET: x64-windows-static

jobs:
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Third Party Dependencies
        uses: actions/cache@v4
        with:
          path: |
            third_party/_downloads
            third_party/webrtc
            third_party/ffmpeg
            third_party/vcpkg
            third_party/vcpkg_installed
          key: deps-${{ runner.os }}-${{ env.WEBRTC_VERSION }}-${{ env.WEBRTC_PLATFORM }}-${{ env.FFMPEG_PACKAGE_VERSION }}-${{ env.FFMPEG_PACKAGE_TARGET }}-${{ env.VCPKG_TARGET_TRIPLET }}-${{ hashFiles('vcpkg.json') }}

      - name: Build And Test Release
        run: |
          call build.cmd test release

      - name: Upload executable
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: peerconnection-client-windows-release
          path: |
            build/release/peerconnection_client.exe
            build/release/peerconnection_client.pdb
            build/release/*.dll
          if-no-files-found: error
